version: 0.0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
environment:
  TreatWarningsAsErrors: true
before_build:
- nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
after_build:
- ps: .\packages\JetBrains.ReSharper.CommandLineTools.2016.1.20160504.105828\tools\inspectcode.exe ValueTypeAssertions.sln --output=InspectCodeOutput.xml --disable-settings-layers:'GlobalAll;GlobalPerProduct;SolutionPersonal;ProjectPersonal' ; fc.exe InspectCodeBaseline.xml InspectCodeOutput.xml
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_informational_version: "{version}-beta"
deploy:
  provider: NuGet
  api_key:
    secure: ohOHAKDLwiS46NIS3DEbwnX6Ggln9CXEe9EKjwVASiRT8Re33GkkHUr+fS/7uz8l
  skip_symbols: false
  artifact: /.*\.nupkg/
